# This is a basic workflow to help you get started with Actions

name: "Schedule Save"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 15 */1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul
      - name: npm install, build, and test
        run: |
          cd .packages/dku-schedule-cralwer
          yarn install
          yarn build
          yarn start:prod
          cd ../..
          git config --global user.name 'junilhwang'
          git config --global user.email 'junil.h@kakao.com'
          git commit -am 'feat: data refresh'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push -u origin master
